### ISSUE TITLE
Arrays of strings incorrectly require `items.properties`

### ISSUE THREAD

**Issue by robjhornby-ts** [tetrascience/ts-ids-validator#10]
The validator is giving me this error:
```
'array' type must contain items.properties
```

On a part of the schema which is an array of strings (not objects):

```
          "comments": {
            "type": "array",
            "items": {
              "type": ["null", "string"]
            }
          },
```

An array only needs `items.properties` if `items.type` is `object` - and then this is an identical rule to `'object' type must contain non-empty 'properties'`, so I think this check can be removed or modified to only apply to arrays of objects.

**Comment by wkopen** [comment]
Accepted. It is a bug.
