### ISSUE TITLE
systems.software and systems.firmware should not require certain fields

### ISSUE THREAD

**Issue by wkopen** [tetrascience/ts-ids-validator#13]
Currently it's reported that
```
root.properties.systems.items.properties.software:
* 'properties' must contain ['last_updated_timestamp', 'serial_number']
root.properties.systems.items.properties.firmware:
* 'properties' must contain ['last_updated_timestamp']
```
But the convention doesn't require that.
Please see the schema template defined in: https://developers.tetrascience.com/docs/ids-design-conventions-schema-templates#firmware
and
https://developers.tetrascience.com/docs/ids-design-conventions-schema-templates#software

**Comment by setiat** [comment]
This is enforcing `properties.keys()` and as per JSON templates for software, `software.properties` should contain three properties : `name`, `version` and `last_updated_timestamp`.
`required: list` check is different than `properties.keys()` check... required list must be exactly `["name","version"]`

Should I just change it to like `properties.key()` check must enforce only the properties mentioned in `required`?

**Comment by kmccormickTetra** [comment]
Not sure if the latest PR will address this also, but I got a slightly different error:
```root.properties.systems:
   * 'properties' must contain ['firmware', 'name', 'serial_number', 'software']```
   I don't think the convention requires these fields, only that there are defined schema for them *if* they are used.

**Comment by wkopen** [comment]
@tariksetia I updated the schema template now and only `name` and `version` is required for `software` and only `vendor`, `model`, `type` is required for `systems`. You can still use the current way to check. I think the convention doc wasn't very clear on that. I updated it. It will address Kevin's question too.

**Comment by setiat** [comment]
> Not sure if the latest PR will address this also, but I got a slightly different error:
> 
> ```
> root.properties.systems:
>    * 'properties' must contain ['firmware', 'name', 'serial_number', 'software']
> ```
> 
> I don't think the convention requires these fields, only that there are defined schema for them _if_ they are used.

I think this was fixed earlier. @kmccormickTetra Could you please check if your are on the latest master branch?
And if you are using the latest one , Could you please pass me the IDS artifact?
