### ISSUE TITLE
Typo's in error messages

### ISSUE THREAD

**Issue by nilsguillermin** [tetrascience/ts-ids-validator#24]
While running the validator on `common/flow-cytometer-intellicyt-ique3/v3.0.0`, obtained the following validation errors

```
root.properties.datacubes:
   * 'measures.value': Dimensionality of data stored in `measures.value` must be equal to `dimesions.minItems` or `dimensions.maxItems`
   * 'measures.value': Type Error. Type must be either be `number` or `string`. It can be nullable
   * 'required' must exist and contain at least ['name','measures','dimensions']
```

The correct spelling would be `measures.values` and `dimensions.minItems`

**Comment by setiat** [comment]
- As per doc : https://developers.tetrascience.com/docs/ids-design-conventions-schema-templates#datacubes-pattern, `measures.value` is correct
- Will fix the typo for `dimensions`
